### ISSUE TITLE
您好，请问关于您博客“https://www.licodeao.top/”首页中间技术栈的标签，在README.md文件中是怎么实现的？可以发下代码参考下吗？

### ISSUE THREAD

**Issue by moyu178666** [Licodeao/Licodeao#1]
您好，请问关于您博客“https://www.licodeao.top/”首页中间技术栈的标签，在README.md文件中是怎么实现的？可以发下代码参考下吗？

**Comment by Licodeao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Licodeao** [comment]
> 您好，请问关于您博客“[https://www.licodeao.top/”首页中间技术栈的标签，在README.md文件中是怎么实现的？可以发下代码参考下吗？](https://www.licodeao.top/%E2%80%9D%E9%A6%96%E9%A1%B5%E4%B8%AD%E9%97%B4%E6%8A%80%E6%9C%AF%E6%A0%88%E7%9A%84%E6%A0%87%E7%AD%BE%EF%BC%8C%E5%9C%A8README.md%E6%96%87%E4%BB%B6%E4%B8%AD%E6%98%AF%E6%80%8E%E4%B9%88%E5%AE%9E%E7%8E%B0%E7%9A%84%EF%BC%9F%E5%8F%AF%E4%BB%A5%E5%8F%91%E4%B8%8B%E4%BB%A3%E7%A0%81%E5%8F%82%E8%80%83%E4%B8%8B%E5%90%97%EF%BC%9F)

你好，关于首页中间技术栈的标签的实现：
1. 你可以先看官方文档中的[注册组件](https://vuepress-theme-reco.recoluan.com/docs/theme/register-components.html)
2. 关于徽标，你可以看看[shields.io官方文档](https://shields.io/)，或者直接[在这里](https://dev.to/envoy_/150-badges-for-github-pnk#skills)找你想要的徽标
3. 具体样式如下，在此基础上你可自行修改
```css
.badgeContainer {
  display: flex;
  display: -webkit-flex;
  flex-direction: row;
  flex-wrap: wrap;
  width: 58vw;
  margin: 0 auto;
}

.badgeContainer img {
  margin: 5px 5px 0 0;
}

@media (max-width: 768px) {
  .badgeContainer {
    width: 90vw;
  }
}
```
5. 若你根据文档顺利地注册组件后，需要在 `README.md` 文件中的 `modules` 模块中导入注册组件，具体为以下实现：
```md
home: true
modules:
  - BannerBrand
  - BadgePlatform -> 徽标组件
  - Blog
  - MdContent
  - Footer
bannerBrand:
  bgImage: "/bg.png"
```
6. 最后，如果还有啥不明白的，欢迎继续评论，感谢您的关注😁
